services:
  node:
    image: node:20.12.1-alpine
    container_name: adonis_node
    working_dir: /work
    tty: true
    environment:
      - HOST=0.0.0.0
    volumes:
      - ./:/work
      - /work/node_modules
    ports:
      - 46533:3333
    depends_on:
      - mysql
      - redis
    networks:
      - adonis_network
  mysql:
    image: mysql:9.0
    container_name: adonis_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ./docker/mysql-data:/var/lib/mysql
    restart: always
    ports:
      - 46534:3306
    networks:
      adonis_network:
        ipv4_address: 172.30.0.3
  redis:
    image: redis:7.2.4
    container_name: adonis_redis
    restart: always
    ports:
      - 46535:6379
    networks:
      - adonis_network

networks:
  adonis_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16